whenever sqlerror exit sql.sqlcode
set echo on feedback on serveroutput on

alter session set container = crashpdb;

begin
  for rec in (
    select username
    from dba_users
    where username in (
      'CRASHSIM_TABLE_LAB',
      'CRASHSIM_SCHEMA_LAB',
      'CRASHSIM_INDEX_LAB'
    )
  ) loop
    execute immediate 'drop user ' || rec.username || ' cascade';
  end loop;
end;
/

create user crashsim_table_lab identified by "CrashSimLab##123" quota unlimited on users;
grant create session, create table, create sequence to crashsim_table_lab;

create table crashsim_table_lab.crash_table_target (
  id number generated by default as identity,
  payload varchar2(100),
  created_at timestamp default systimestamp,
  constraint crash_table_target_pk primary key (id)
);

insert into crashsim_table_lab.crash_table_target (payload)
select 'table-loss-row-' || level
from dual
connect by level <= 10;

create user crashsim_schema_lab identified by "CrashSimLab##123" quota unlimited on users;
grant create session, create table, create sequence to crashsim_schema_lab;

create table crashsim_schema_lab.schema_drop_target (
  id number primary key,
  payload varchar2(100)
);

insert into crashsim_schema_lab.schema_drop_target
select level, 'schema-loss-row-' || level
from dual
connect by level <= 10;

create user crashsim_index_lab identified by "CrashSimLab##123" quota unlimited on users;
grant create session, create table, create sequence to crashsim_index_lab;

create table crashsim_index_lab.index_target (
  id number primary key,
  lookup_value varchar2(30),
  payload varchar2(100)
);

insert into crashsim_index_lab.index_target
select level, 'L' || mod(level, 5), 'index-loss-row-' || level
from dual
connect by level <= 50;

create index crashsim_index_lab.index_target_lookup_ix
  on crashsim_index_lab.index_target (lookup_value);

commit;

select owner, table_name
from dba_tables
where owner like 'CRASHSIM\_%' escape '\'
order by owner, table_name;

select owner, index_name, uniqueness
from dba_indexes
where owner like 'CRASHSIM\_%' escape '\'
order by owner, index_name;

alter session set container = cdb$root;
