#!/usr/bin/env bash
#
# CrashSimulator V2 - Oracle HA/DR/backup and recovery practice framework.
#
# Default behavior is safe: discovery, listing, and dry-run planning do not
# damage the database. Destructive actions require --execute and confirmation.

set -uo pipefail

if [[ -z "${BASH_VERSINFO:-}" || "${BASH_VERSINFO[0]}" -lt 4 ]]; then
  echo "ERROR: CrashSimulator V2 requires Bash 4 or later. Current Bash: ${BASH_VERSION:-unknown}" >&2
  echo "On Oracle Linux, run it with /bin/bash from the database host." >&2
  exit 2
fi

VERSION="2.0.2-beta"
SUCCESS=0
FAIL=1

PROGRAM="$(basename "$0")"
BASH_EXECUTABLE="${BASH:-bash}"
SCRIPT_SOURCE="${BASH_SOURCE[0]:-$0}"
case "$SCRIPT_SOURCE" in
  */*)
    SCRIPT_PATH="$(cd -P "$(dirname "$SCRIPT_SOURCE")" >/dev/null 2>&1 && pwd)/$(basename "$SCRIPT_SOURCE")"
    ;;
  *)
    SCRIPT_PATH="$(command -v "$SCRIPT_SOURCE" 2>/dev/null || true)"
    [[ -n "$SCRIPT_PATH" ]] || SCRIPT_PATH="./$SCRIPT_SOURCE"
    ;;
esac
MODE="menu"
SCENARIO_ID=""
TARGET_PDB="${CRASHSIM_PDB:-}"
TARGET_SCHEMA="${CRASHSIM_SCHEMA:-}"
TARGET_FILE_NO="${CRASHSIM_FILE_NO:-}"
PFILE_PATH="${CRASHSIM_PFILE:-}"
SYS_PASSWORD="${CRASHSIM_SYS_PASSWORD:-}"
SERVICE_NAME="${CRASHSIM_SERVICE_NAME:-}"
SYSBACKUP_USER="${CRASHSIM_SYSBACKUP_USER:-C##DBLCMUSER}"
TEMPFILE_SIZE="${CRASHSIM_TEMPFILE_SIZE:-100m}"
GRID_USER="${CRASHSIM_GRID_USER:-grid}"
LOCAL_ONLY="${CRASHSIM_LOCAL_ONLY:-0}"
MAX_TARGETS="${CRASHSIM_MAX_TARGETS:-}"
PIECE_HANDLE="${CRASHSIM_PIECE_HANDLE:-}"
REPORT_DEEP_VALIDATE="${CRASHSIM_REPORT_DEEP_VALIDATE:-0}"
RMAN_CATALOG_CONNECT="${CRASHSIM_RMAN_CATALOG:-}"
BASELINE_TAG_PREFIX="${CRASHSIM_BASELINE_TAG_PREFIX:-CSIM_BASE}"
FRA_PRESSURE_TARGET_PCT="${CRASHSIM_FRA_PRESSURE_TARGET_PCT:-98}"
FRA_PRESSURE_HEADROOM_MB="${CRASHSIM_FRA_PRESSURE_HEADROOM_MB:-64}"
TEMP_EXHAUST_MB="${CRASHSIM_TEMP_EXHAUST_MB:-512}"
ORDS_SERVICE_NAME="${CRASHSIM_ORDS_SERVICE:-ords}"
ORDS_CONFIG_DIR="${CRASHSIM_ORDS_CONFIG_DIR:-/etc/ords/config}"
ORDS_URL="${CRASHSIM_ORDS_URL:-http://localhost:8080/ords/}"
ORDS_LB_URL="${CRASHSIM_ORDS_LB_URL:-}"
ORDS_DB_POOL="${CRASHSIM_ORDS_DB_POOL:-default}"
ORDS_PRIV_HELPER="${CRASHSIM_ORDS_PRIV_HELPER:-/usr/local/bin/crashsim_ords_priv}"
APEX_IMAGES_DIR="${CRASHSIM_APEX_IMAGES_DIR:-}"
APEX_SESSION_DRIVER="${CRASHSIM_APEX_SESSION_DRIVER:-}"
APEX_SESSION_URL="${CRASHSIM_APEX_SESSION_URL:-}"
APEX_SESSION_USERNAME="${CRASHSIM_APEX_SESSION_USERNAME:-}"
APEX_SESSION_PASSWORD="${CRASHSIM_APEX_SESSION_PASSWORD:-}"
APEX_SESSION_SUCCESS_SELECTOR="${CRASHSIM_APEX_SESSION_SUCCESS_SELECTOR:-}"
APEX_SESSION_USERNAME_SELECTOR="${CRASHSIM_APEX_SESSION_USERNAME_SELECTOR:-}"
APEX_SESSION_PASSWORD_SELECTOR="${CRASHSIM_APEX_SESSION_PASSWORD_SELECTOR:-}"
APEX_SESSION_SUBMIT_SELECTOR="${CRASHSIM_APEX_SESSION_SUBMIT_SELECTOR:-}"
APEX_SESSION_DURATION="${CRASHSIM_APEX_SESSION_DURATION:-90}"
APEX_SESSION_INTERVAL="${CRASHSIM_APEX_SESSION_INTERVAL:-10}"
APEX_SESSION_HEADLESS="${CRASHSIM_APEX_SESSION_HEADLESS:-1}"
AUDIT_RETAIN="${CRASHSIM_AUDIT_RETAIN:-1}"
AUDIT_RETENTION_DAYS="${CRASHSIM_AUDIT_RETENTION_DAYS:-365}"
AUDIT_DIR="${CRASHSIM_AUDIT_DIR:-}"
AUDIT_STREAM_CAPTURE="${CRASHSIM_AUDIT_STREAM_CAPTURE:-auto}"
AUTO_SCORECARD="${CRASHSIM_AUTO_SCORECARD:-1}"
DESTRUCTIVE_LAB_ACK="${CRASHSIM_ACCEPT_DESTRUCTIVE_LAB:-}"
TOPOLOGY_CACHE_TTL_SECONDS="${CRASHSIM_TOPOLOGY_CACHE_TTL_SECONDS:-300}"
TOPOLOGY_CACHE_REFRESH=0
TOPOLOGY_CACHE_DISABLED="${CRASHSIM_DISABLE_TOPOLOGY_CACHE:-0}"
SECRET_SCAN_PATH="${CRASHSIM_SECRET_SCAN_PATH:-.}"
SANITIZE_SOURCE_DIR="${CRASHSIM_SANITIZE_SOURCE_DIR:-.}"
SANITIZE_OUTPUT_DIR="${CRASHSIM_SANITIZE_OUTPUT_DIR:-}"
HTML_OUTPUT=0
HTML_TARGET="${CRASHSIM_HTML_TARGET:-}"
REVIEW_TARGET="${CRASHSIM_REVIEW_TARGET:-}"
MAA_APP_NAME="${CRASHSIM_MAA_APP_NAME:-}"
MAA_LOCAL_RTO="${CRASHSIM_MAA_LOCAL_RTO:-}"
MAA_LOCAL_RPO="${CRASHSIM_MAA_LOCAL_RPO:-}"
MAA_DR_RTO="${CRASHSIM_MAA_DR_RTO:-}"
MAA_DR_RPO="${CRASHSIM_MAA_DR_RPO:-}"
MAA_PLANNED_RTO="${CRASHSIM_MAA_PLANNED_RTO:-}"
MAA_PLANNED_RPO="${CRASHSIM_MAA_PLANNED_RPO:-}"
MAA_CRITICALITY="${CRASHSIM_MAA_CRITICALITY:-}"
MAA_LOCAL_HA_TARGET="${CRASHSIM_MAA_LOCAL_HA_TARGET:-}"
MAA_DR_REQUIRED="${CRASHSIM_MAA_DR_REQUIRED:-}"
MAA_AUTOMATIC_FAILOVER_REQUIRED="${CRASHSIM_MAA_AUTOMATIC_FAILOVER_REQUIRED:-}"
MAA_ACTIVE_ACTIVE_REQUIRED="${CRASHSIM_MAA_ACTIVE_ACTIVE_REQUIRED:-}"
MAA_PLATFORM_HINT="${CRASHSIM_MAA_PLATFORM_HINT:-}"
MAA_STANDBY_SCOPE="${CRASHSIM_MAA_STANDBY_SCOPE:-unknown}"
ADB_WALLET_DIR="${CRASHSIM_ADB_WALLET_DIR:-}"
ADB_CONNECT_ALIAS="${CRASHSIM_ADB_CONNECT_ALIAS:-}"
ADB_CONNECT_DESCRIPTOR="${CRASHSIM_ADB_CONNECT_DESCRIPTOR:-}"
ADB_SERVICE_LEVEL="${CRASHSIM_ADB_SERVICE_LEVEL:-low}"
ADB_USER="${CRASHSIM_ADB_USER:-ADMIN}"
ADB_PASSWORD_ENV="${CRASHSIM_ADB_PASSWORD_ENV:-CRASHSIM_ADB_PASSWORD}"
ADB_WALLET_PASSWORD_ENV="${CRASHSIM_ADB_WALLET_PASSWORD_ENV:-CRASHSIM_ADB_WALLET_PASSWORD}"
ADB_PYTHON="${CRASHSIM_ADB_PYTHON:-python3}"
ADB_TLS_MODE="${CRASHSIM_ADB_TLS_MODE:-mTLS}"
ADB_OCID="${CRASHSIM_ADB_OCID:-}"
ADB_COMPARTMENT_OCID="${CRASHSIM_ADB_COMPARTMENT_OCID:-}"
ADB_REGION="${CRASHSIM_ADB_REGION:-}"
ADB_OCI_PROFILE="${CRASHSIM_ADB_OCI_PROFILE:-DEFAULT}"
ADB_OCI_CONFIG_FILE="${CRASHSIM_ADB_OCI_CONFIG_FILE:-}"
ADB_OCI_AUTH="${CRASHSIM_ADB_OCI_AUTH:-}"
ADB_APEX_URL="${CRASHSIM_ADB_APEX_URL:-}"
ADB_DATABASE_ACTIONS_URL="${CRASHSIM_ADB_DATABASE_ACTIONS_URL:-}"
ADB_PRIVATE_ENDPOINT="${CRASHSIM_ADB_PRIVATE_ENDPOINT:-}"
ADB_SCENARIO_ID="${CRASHSIM_ADB_SCENARIO:-}"
LOG_DIR="${CRASHSIM_LOG_DIR:-}"
CONFIG_FILE="${CRASHSIM_CONFIG:-}"
CONFIG_SOURCE=""
CONFIG_EXPLICIT=0
CONFIG_DISABLED=0
CONFIG_LOADED=0
CONFIG_TEMPLATE_FILE=""
WORK_DIR=""
RUN_ID="$(date +%Y%m%d_%H%M%S)"
EXECUTE=0
ASSUME_YES=0
VERBOSE=0
SQLPLUS_BIN="${SQLPLUS:-}"
RMAN_BIN="${RMAN:-}"
SQLPLUS_LOGON="${CRASHSIM_SQLPLUS_LOGON:-/ as sysdba}"
ORACLE_USER_REQUIRED="${CRASHSIM_ORACLE_USER_REQUIRED:-0}"
MANIFEST_FILE="${CRASHSIM_MANIFEST:-}"
MANIFEST_FROM_ARG="${CRASHSIM_MANIFEST:+1}"
MANIFEST_FROM_ARG="${MANIFEST_FROM_ARG:-0}"
CURRENT_SCENARIO_ID=""
PLANNING_ONLY=0
AUDIT_RUN_DIR=""
AUDIT_MARKER_FILE=""
AUDIT_STDOUT_FILE=""
AUDIT_STDERR_FILE=""
AUDIT_STDOUT_FIFO=""
AUDIT_STDERR_FIFO=""
AUDIT_STARTED=0
AUDIT_FINALIZED=0
AUTO_SCORECARD_REFRESHING=0
MENU_SCHEMA_PROMPTED_SCENARIO=""

DB_NAME=""
DB_UNIQUE_NAME=""
DB_ROLE=""
DB_OPEN_MODE=""
DB_CDB=""
DB_PROTECTION_MODE=""
DB_SWITCHOVER_STATUS=""
INSTANCE_NAME=""
HOST_NAME=""
INSTANCE_STATUS=""
INSTANCE_PARALLEL=""
INSTANCE_THREAD=""
ORACLE_BASE_DETECTED=""
SPFILE_PATH=""
FRA_PATH=""
PASSWORD_FILE_PATH=""
CLUSTER_TYPE="UNKNOWN"
STORAGE_TYPE="UNKNOWN"
GI_MANAGED=0
DISCOVERED=0

declare -a PDB_ROWS=()
declare -a TARGET_ROWS=()
declare -a CONFIG_APPLIED=()
declare -a CONFIG_SKIPPED=()
declare -a CONFIG_WARNINGS=()
declare -a MENU_ARTIFACT_FILES=()
declare -a ACTION_KINDS=()
declare -a ACTION_TARGETS=()
declare -a ACTION_DETAILS=()
declare -a PLAN_TARGET_PATHS=()
declare -a PLAN_TARGET_PDBS=()
declare -a PLAN_TARGET_CON_IDS=()
declare -a PLAN_TARGET_FILE_NOS=()
declare -a PLAN_TARGET_TABLESPACES=()
declare -a RESTORE_ORIGINALS=()
declare -a RESTORE_BACKUPS=()
declare -a RESTORE_METHODS=()
declare -a RECOVER_FILE_NOS=()
declare -a RECOVER_TEMPFILE_PATHS=()
declare -a ORIGINAL_ARGS=("$@")
RENAME_COUNT=0
RECOVER_TEMPFILE_TABLESPACE=""
RECOVER_TEMPFILE_PDB=""

declare -a SCENARIO_IDS=()
declare -A SCENARIO_TITLE=()
declare -A SCENARIO_GROUP=()
declare -A SCENARIO_SCOPE=()
declare -A SCENARIO_IMPACT=()
declare -A SCENARIO_REQUIRES=()
declare -A SCENARIO_HANDLER=()
declare -A SCENARIO_NOTES=()
declare -A MAA_EVIDENCE=()
declare -A BACKUP_EVIDENCE=()
declare -A RPO_EVIDENCE=()
declare -A APEX_ORDS_EVIDENCE=()
declare -A ADB_EVIDENCE=()
declare -A PREP_EVIDENCE=()
declare -a PREP_IDS=()
declare -A PREP_TITLE=()
declare -A PREP_STATUS=()
declare -A PREP_REQUIRED=()
declare -A PREP_EVIDENCE_TEXT=()
declare -A PREP_ACTION=()
declare -A PREP_AUTO=()
declare -A PREP_COMMAND=()
declare -A PREP_NOTES=()
declare -a ADB_SCENARIO_IDS=()
declare -A ADB_SCENARIO_TITLE=()
declare -A ADB_SCENARIO_AREA=()
declare -A ADB_SCENARIO_VALIDATION=()
declare -A ADB_SCENARIO_RECOVERY=()
declare -A ADB_SCENARIO_HELPER=()

SCENARIO_VALIDATION_STATUS=""
SCENARIO_VALIDATION_REASON=""
SCENARIO_VALIDATION_OUTPUT=""

