register_scenario() {
  local id="$1"
  local title="$2"
  local group="$3"
  local scope="$4"
  local impact="$5"
  local requires="$6"
  local handler="$7"
  local notes="$8"
  SCENARIO_IDS+=("$id")
  SCENARIO_TITLE["$id"]="$title"
  SCENARIO_GROUP["$id"]="$group"
  SCENARIO_SCOPE["$id"]="$scope"
  SCENARIO_IMPACT["$id"]="$impact"
  SCENARIO_REQUIRES["$id"]="$requires"
  SCENARIO_HANDLER["$id"]="$handler"
  SCENARIO_NOTES["$id"]="$notes"
}

register_scenarios() {
  register_scenario "1"  "Loss of one control file"                         "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_control_one"       "Renames one control file and optionally aborts the target instance."
  register_scenario "2"  "Loss of all control files"                         "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_control_all"       "Renames all control files and optionally aborts the target instance."
  register_scenario "3"  "Loss of one member from current redo group"         "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_redo_member_one"   "Targets one member of the current redo group."
  register_scenario "4"  "Loss of all members from current redo group"        "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_current_redo_all"  "Targets all members of the current redo group."
  register_scenario "5"  "Loss of one non-system datafile"                   "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_non_system_one"    "Does not assume USERS exists."
  register_scenario "6"  "Loss of one temporary file"                        "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_temp_one"          "Targets a database temporary file."
  register_scenario "7"  "Loss of one SYSTEM datafile"                       "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_system_one"        "High-impact SYSTEM datafile scenario."
  register_scenario "8"  "Loss of one UNDO datafile"                         "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_undo_one"          "Targets an online UNDO tablespace file."
  register_scenario "9"  "Loss of a read-only tablespace"                    "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_readonly_tbs"      "Targets all files in one read-only tablespace."
  register_scenario "10" "Loss of an index-only tablespace"                  "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_indexonly_tbs"     "Targets a tablespace with indexes and no tables."
  register_scenario "11" "Drop non-unique indexes outside Oracle schemas"     "Logical"    "CDB/non-CDB" "logical"      "primary"           "scenario_drop_indexes"      "Logical object loss for rebuild practice."
  register_scenario "12" "Loss of a non-system tablespace"                   "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_non_system_tbs"    "Targets all files in one non-system permanent tablespace."
  register_scenario "13" "Loss of a temporary tablespace"                    "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_temp_tbs"          "Targets all files in one temporary tablespace."
  register_scenario "14" "Loss of SYSTEM tablespace"                         "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_system_tbs"        "Targets all SYSTEM datafiles."
  register_scenario "15" "Loss of UNDO tablespace"                           "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_undo_tbs"          "Targets all files in one UNDO tablespace."
  register_scenario "16" "Loss of password file"                             "Config"     "CDB/non-CDB" "destructive" "primary"           "scenario_password_file"     "Uses srvctl metadata where available; falls back to ORACLE_HOME/dbs."
  register_scenario "17" "Loss of all datafiles"                             "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_all_datafiles"     "Very high-impact full database restore practice."
  register_scenario "18" "Loss of one member from multiplexed redo group"     "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_redo_member_one"   "Requires a group with more than one member."
  register_scenario "19" "Loss of all inactive redo groups"                  "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_inactive_redo_all" "Targets inactive redo groups."
  register_scenario "20" "Loss of all active redo groups"                    "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_active_redo_all"   "Switches logfile first, then targets active groups."
  register_scenario "21" "Loss of all current redo group members"            "Core"       "CDB/non-CDB" "destructive" "primary"           "scenario_current_redo_all"  "Targets current redo group members."
  register_scenario "22" "Datafile header corruption"                        "Corrupt"    "CDB/non-CDB" "destructive" "primary"           "scenario_file_header_corrupt" "Overwrites one block in a SYSTEM datafile."
  register_scenario "23" "Control file corruption"                           "Corrupt"    "CDB/non-CDB" "destructive" "primary"           "scenario_control_corrupt"   "Overwrites bytes in all control files."
  register_scenario "24" "Redo log corruption"                               "Corrupt"    "CDB/non-CDB" "destructive" "primary"           "scenario_redo_corrupt"      "Overwrites bytes in active redo members."
  register_scenario "25" "Loss of RMAN backup pieces"                        "Backup"     "CDB/non-CDB" "destructive" "any"               "scenario_rman_backups"      "Targets backup pieces known in V\$BACKUP_PIECE."
  register_scenario "26" "Loss of SPFILE"                                    "Config"     "CDB/non-CDB" "destructive" "primary"           "scenario_spfile"            "Targets the active SPFILE."
  register_scenario "27" "Loss of SQL*Net config files"                      "Config"     "CDB/non-CDB" "destructive" "any"               "scenario_sqlnet"            "Targets listener.ora, tnsnames.ora, sqlnet.ora if present."
  register_scenario "28" "Loss of ORACLE_HOME"                               "Config"     "CDB/non-CDB" "destructive" "any"               "scenario_oracle_home"       "Renames ORACLE_HOME; lab only."
  register_scenario "29" "Loss of FRA destination"                           "Backup"     "CDB/non-CDB" "destructive" "primary"           "scenario_fra"               "Renames configured FRA destination."
  register_scenario "30" "PDB loss of one non-system datafile"               "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_non_system_one" "Requires --pdb."
  register_scenario "31" "PDB loss of one temporary file"                    "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_temp_one"      "Requires --pdb."
  register_scenario "32" "PDB loss of one SYSTEM datafile"                   "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_system_one"    "Requires --pdb."
  register_scenario "33" "PDB loss of one UNDO datafile"                     "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_undo_one"      "Requires local undo and --pdb."
  register_scenario "34" "PDB loss of read-only tablespace"                  "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_readonly_tbs"  "Requires --pdb."
  register_scenario "35" "PDB loss of index-only tablespace"                 "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_indexonly_tbs" "Requires --pdb."
  register_scenario "36" "PDB drop non-unique indexes"                       "PDB"        "PDB"        "logical"      "cdb,pdb,primary"   "scenario_pdb_drop_indexes"  "Requires --pdb."
  register_scenario "37" "PDB loss of non-system tablespace"                 "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_non_system_tbs" "Requires --pdb."
  register_scenario "38" "PDB loss of temporary tablespace"                  "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_temp_tbs"      "Requires --pdb."
  register_scenario "39" "PDB loss of SYSTEM tablespace"                     "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_system_tbs"    "Requires --pdb."
  register_scenario "40" "PDB loss of UNDO tablespace"                       "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_undo_tbs"      "Requires --pdb."
  register_scenario "41" "PDB loss of all datafiles"                         "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_all_datafiles" "Requires --pdb."
  register_scenario "42" "PDB SYSTEM file header corruption"                 "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_pdb_file_header_corrupt" "Requires --pdb."
  register_scenario "43" "PDB loss of one user table"                        "PDB"        "PDB"        "logical"      "cdb,pdb,primary"   "scenario_pdb_drop_table"    "Requires --pdb."
  register_scenario "44" "PDB loss of one user schema"                       "PDB"        "PDB"        "logical"      "cdb,pdb,primary"   "scenario_pdb_drop_schema"   "Requires --pdb."
  register_scenario "45" "Drop selected PDB including datafiles"             "PDB"        "PDB"        "destructive" "cdb,pdb,primary"   "scenario_drop_pdb"          "Requires --pdb."
  register_scenario "46" "ASM/FEX data storage unavailable"                  "ASM"        "ASM/FEX"    "destructive" "asm"               "scenario_asm_diskgroup_unavailable" "Plans ASM disk group or FEX/ACFS managed-storage outage practice; execution requires a provider-aware handler."
  register_scenario "47" "OCR loss or restore drill"                         "GI"         "Cluster"    "destructive" "gi"                "scenario_ocr_restore_drill" "Plans OCR backup/restore practice; execution requires root/Grid procedure approval."
  register_scenario "48" "Voting disk loss or restore drill"                 "GI"         "Cluster"    "destructive" "gi"                "scenario_voting_disk_drill" "Plans voting disk replacement practice; execution requires root/Grid procedure approval."
  register_scenario "49" "ASM/FEX SPFILE loss"                              "ASM"        "ASM/FEX"    "destructive" "asm"               "scenario_asm_spfile_loss"   "Plans ASM or FEX/ACFS managed SPFILE loss practice; execution requires a provider-aware handler."
  register_scenario "50" "Standby managed recovery cancelled"                "DataGuard"  "Standby"    "logical"      "standby"           "scenario_standby_apply_cancel" "For physical standby apply practice."
  register_scenario "51" "Primary transport destination deferred"            "DataGuard"  "Primary"    "logical"      "primary,dg"        "scenario_primary_transport_defer" "Defers the first remote archive destination."
  register_scenario "52" "Data Guard broker configuration unavailable"       "DataGuard"  "DG"         "logical"      "dg"                "scenario_dg_broker_config_unavailable" "Plan-only broker outage drill with SQL/DGMGRL evidence."
  register_scenario "53" "Active Data Guard read-only session pressure"      "ADG"        "Standby"    "logical"      "standby"           "scenario_adg_readonly_session_pressure" "Read-only ADG pressure readiness evidence for READ ONLY WITH APPLY standbys."
  register_scenario "54" "Snapshot standby conversion practice"              "DataGuard"  "Standby"    "logical"      "standby"           "scenario_snapshot_standby_conversion_practice" "Plan-only snapshot-standby conversion readiness evidence."
  register_scenario "55" "RAC abort one instance"                            "RAC"        "RAC"        "destructive" "rac"               "scenario_rac_abort_instance" "Uses srvctl where available."
  register_scenario "56" "RAC service relocation failure practice"           "RAC"        "RAC"        "logical"      "rac"               "scenario_rac_service_relocation" "Relocates a singleton service when possible, or stop/start validates an all-instances service."
  register_scenario "57" "Listener config unavailable"                       "Network"    "CDB/non-CDB" "destructive" "any"               "scenario_sqlnet"            "Alias for network file loss."
  register_scenario "58" "TDE wallet or keystore unavailable"                "Security"   "CDB/non-CDB" "destructive" "primary"           "scenario_tde_wallet"        "Renames detected wallet root if configured."
  register_scenario "59" "Missing archived redo log"                         "Backup"     "CDB/non-CDB" "destructive" "primary"           "scenario_archivelog_loss"   "Targets one archived log known to the control file."
  register_scenario "60" "Recovery catalog unavailable"                      "Backup"     "External"   "logical"      "any"               "scenario_recovery_catalog_unavailable" "Validates catalog connectivity and NOCATALOG fallback behavior."
  register_scenario "61" "FRA reaches critical utilization"                  "Backup"     "CDB/non-CDB" "destructive" "primary"           "scenario_fra_full"          "Safely simulates FRA pressure by shrinking DB_RECOVERY_FILE_DEST_SIZE near current usage."
  register_scenario "62" "Missing required archived log during recovery"      "Backup"     "CDB/non-CDB" "destructive" "primary"           "scenario_required_archivelog_recovery_gap" "Targets one available archived log and generates recovery-decision evidence."
  register_scenario "63" "TEMP tablespace exhaustion"                        "Core"       "CDB/non-CDB" "logical"      "primary"           "scenario_temp_exhaustion"   "Runs a controlled disposable TEMP-consuming workload; optional --pdb context is supported."
  register_scenario "64" "RTO validation drill"                              "Compliance" "CDB/non-CDB" "logical"      "any"               "scenario_rto_validation"    "Read-only report comparing latest recovery manifest timing to supplied RTO objectives."
  register_scenario "65" "RPO validation drill"                              "Compliance" "CDB/non-CDB" "logical"      "any"               "scenario_rpo_validation"    "Read-only report estimating recoverable-data window from archived redo, backups, and DG evidence."
  register_scenario "66" "FSFO observer unavailable"                         "DataGuard"  "DG"         "logical"      "dg"                "scenario_fsfo_observer_unavailable" "Plans observer outage practice and captures broker/SQL FSFO evidence."
  register_scenario "67" "Data Guard apply lag exceeds SLA"                  "DataGuard"  "Standby"    "logical"      "standby"           "scenario_dg_apply_lag"      "Pauses standby apply to create measurable lag, then recovery restarts apply."
  register_scenario "68" "Data Guard transport network partition"            "DataGuard"  "Primary"    "logical"      "primary,dg"        "scenario_dg_transport_partition" "Defers one remote standby archive destination to simulate transport isolation."
  register_scenario "69" "Standby redo log misconfiguration review"          "DataGuard"  "DG"         "logical"      "dg"                "scenario_standby_redo_log_misconfig" "Read-only SRL sizing/count review against online redo threads."
  register_scenario "70" "RAC VIP relocation drill"                          "RAC"        "RAC"        "logical"      "rac,gi"            "scenario_rac_vip_relocation" "Plans VIP relocation and client survivability validation."
  register_scenario "71" "RAC service placement failure"                     "RAC"        "RAC"        "logical"      "rac"               "scenario_rac_service_placement_failure" "Stops/starts one running service on an instance to validate placement recovery."
  register_scenario "72" "ASM/FEX storage component failure"                 "ASM"        "ASM/FEX"    "destructive" "asm"               "scenario_asm_single_disk_failure" "Plans single-disk failure for redundant ASM disk groups or provider-managed FEX/ACFS storage-component review."
  register_scenario "73" "ORDS service unavailable"                          "APEX/ORDS"  "Application" "logical"     "any"               "scenario_ords_service_unavailable" "Stops the ORDS systemd service when OS service control is available."
  register_scenario "74" "ORDS configuration unavailable"                    "APEX/ORDS"  "Application" "destructive" "any"               "scenario_ords_config_unavailable" "Renames ORDS config only when the config directory is writable; otherwise plan-only."
  register_scenario "75" "ORDS database pool misconfiguration"               "APEX/ORDS"  "Application" "logical"     "any"               "scenario_ords_pool_misconfiguration" "Reversible ORDS pool service-name misconfiguration drill when service restart privileges are approved."
  register_scenario "76" "APEX/ORDS runtime account locked"                  "APEX/ORDS"  "Application" "logical"     "any"               "scenario_apex_runtime_account_locked" "Locks an available APEX/ORDS runtime account and validates unlock recovery."
  register_scenario "77" "APEX static resources unavailable"                 "APEX/ORDS"  "Application" "destructive" "any"               "scenario_apex_static_resources_unavailable" "Renames APEX images/static directory when explicitly configured and writable."
  register_scenario "78" "APEX application availability validation after recovery" "APEX/ORDS" "Application" "logical" "any"         "scenario_apex_application_availability_validation" "Read-only ORDS/APEX smoke evidence after database/PDB recovery."
  register_scenario "79" "ORDS node unavailable behind load balancer"         "APEX/ORDS"  "Application" "logical"     "any"               "scenario_ords_lb_node_unavailable" "Stops local ORDS service and validates optional load-balancer URL."
  register_scenario "80" "APEX session continuity test"                      "APEX/ORDS"  "Application" "logical"     "any"               "scenario_apex_session_continuity" "Read-only APEX/ORDS continuity evidence, with optional seeded browser-session driver for full validation."
  register_scenario "81" "APEX mail queue and configuration validation"       "APEX/ORDS"  "Application" "logical"     "any"               "scenario_apex_mail_config_validation" "Read-only SMTP/wallet/ACL evidence for notification recovery readiness."
  register_scenario "82" "APEX upgrade or patch rollback readiness"           "APEX/ORDS"  "Application" "logical"     "any"               "scenario_apex_patch_rollback_readiness" "Read-only pre/post APEX version, object, and runtime-account evidence."
  register_scenario "83" "Application Continuity replay validation"           "Services"   "Application" "logical"     "any"               "scenario_ac_tac_replay_validation" "Validates AC/TAC service metadata and plans replay-safe client drill evidence."
  register_scenario "84" "FAN notification unavailable"                       "Services"   "RAC/GI"      "logical"     "rac,gi"            "scenario_fan_ons_unavailable" "Captures FAN/ONS/service evidence and plans notification outage validation."
  register_scenario "85" "Planned Data Guard switchover"                      "DataGuard"  "DG"          "logical"     "dg"                "scenario_dg_switchover_drill" "Plan-only DGMGRL/SQL readiness drill for planned switchover."
  register_scenario "86" "Data Guard failback rehearsal"                      "DataGuard"  "DG"          "logical"     "dg"                "scenario_dg_failback_rehearsal" "Plan-only failback/reinstate readiness drill after failover or switchover."
  register_scenario "87" "Role-based service validation"                      "Services"   "RAC/DG"      "logical"     "rac"               "scenario_role_based_service_validation" "Read-only srvctl/SQL evidence for PRIMARY and STANDBY role-scoped services."
  register_scenario "88" "PDB point-in-time recovery drill"                   "PDB"        "PDB"        "logical"     "cdb,pdb,primary"   "scenario_pdb_pitr_drill" "Generates RMAN PDB PITR validation/runbook evidence; execution remains operator-approved."
  register_scenario "89" "Guaranteed restore point rollback"                  "Recovery"   "CDB/non-CDB" "logical"     "primary"           "scenario_guaranteed_restore_point_drill" "Validates Flashback/GRP posture and generates rollback runbook evidence."
  register_scenario "90" "Database patch rollback readiness"                  "Lifecycle"  "CDB/non-CDB" "logical"     "primary"           "scenario_database_patch_rollback_readiness" "Read-only patch fallback readiness review for backups, GRP, Data Guard, and services."
  register_scenario "EXA01" "Exadata cell failure review"                     "Exadata"    "Platform"   "logical"     "any"               "scenario_exadata_cell_failure_review" "Read-only Exadata cell/storage evidence when Exadata tooling is present; otherwise plan-only."
  register_scenario "EXA02" "Exadata storage server outage"                   "Exadata"    "Platform"   "logical"     "any"               "scenario_exadata_storage_server_outage" "Plan-only storage-server outage runbook with cellcli/exachk evidence hooks."
  register_scenario "EXA03" "Exadata Smart Scan validation"                   "Exadata"    "Platform"   "logical"     "any"               "scenario_exadata_smart_scan_validation" "Read-only Smart Scan readiness and validation planning."
  register_scenario "EXA04" "Exadata Flash Cache failure"                     "Exadata"    "Platform"   "logical"     "any"               "scenario_exadata_flash_cache_failure" "Plan-only Flash Cache failure/recovery evidence and runbook."
  register_scenario "OCI01" "OCI Base DB backup policy validation"            "OCI DB"     "Cloud"      "logical"     "any"               "scenario_oci_db_backup_policy_validation" "Read-only OCI/DB backup-policy posture and DBaaS backup evidence."
  register_scenario "OCI02" "OCI cross-region backup recovery"                "OCI DB"     "Cloud"      "logical"     "any"               "scenario_oci_cross_region_backup_recovery" "Plan-only cross-region backup restore validation drill."
  register_scenario "OCI03" "OCI database system failover"                    "OCI DB"     "Cloud"      "logical"     "any"               "scenario_oci_db_system_failover" "Plan-only DB system failure/recovery evidence for OCI Base DB."
  register_scenario "OCI04" "OCI VCN connectivity loss"                       "OCI DB"     "Cloud"      "logical"     "any"               "scenario_oci_vcn_connectivity_loss" "Read-only network-context evidence and plan-only VCN connectivity drill."
  register_scenario "OCI05" "OCI NSG misconfiguration"                        "OCI DB"     "Cloud"      "logical"     "any"               "scenario_oci_nsg_misconfiguration" "Plan-only NSG/security-list misconfiguration validation with OCI evidence hooks."
  register_scenario "GG01" "GoldenGate Extract stopped"                       "GoldenGate" "Replication" "logical"    "any"               "scenario_goldengate_extract_stopped" "Read-only GoldenGate deployment/process evidence and plan-only Extract stop drill."
  register_scenario "GG02" "GoldenGate Replicat stopped"                      "GoldenGate" "Replication" "logical"    "any"               "scenario_goldengate_replicat_stopped" "Read-only GoldenGate deployment/process evidence and plan-only Replicat stop drill."
  register_scenario "GG03" "GoldenGate lag exceeds SLA"                       "GoldenGate" "Replication" "logical"    "any"               "scenario_goldengate_lag_sla" "Read-only lag evidence hooks and SLA runbook for GoldenGate."
  register_scenario "GG04" "GoldenGate trail corruption"                      "GoldenGate" "Replication" "destructive" "any"              "scenario_goldengate_trail_corruption" "Plan-only trail corruption/loss recovery runbook; no file changes are automated."
}

register_adb_scenario() {
  local id="$1"
  local title="$2"
  local area="$3"
  local validation="$4"
  local recovery="$5"
  local helper="$6"

  ADB_SCENARIO_IDS+=("$id")
  ADB_SCENARIO_TITLE["$id"]="$title"
  ADB_SCENARIO_AREA["$id"]="$area"
  ADB_SCENARIO_VALIDATION["$id"]="$validation"
  ADB_SCENARIO_RECOVERY["$id"]="$recovery"
  ADB_SCENARIO_HELPER["$id"]="$helper"
}

register_adb_scenarios() {
  [[ "${#ADB_SCENARIO_IDS[@]}" -eq 0 ]] || return "$SUCCESS"

  register_adb_scenario "ADB01" "Drop critical application table" "Logical recovery" "Live SQL connection, disposable lab table, flashback eligibility, clone/export fallback." "Flashback Table, PITR clone, Data Pump/object merge, application validation." "Future seeded logical helper."
  register_adb_scenario "ADB02" "Drop application schema" "Logical recovery" "Live SQL connection, disposable schema, grants/object inventory, export or clone/PITR path." "Clone/export recovery, user/grant restoration, application validation." "Plan/runbook first; destructive helper pending."
  register_adb_scenario "ADB03" "Mass DELETE without WHERE clause" "Logical recovery" "Live SQL connection, disposable lab table, before/after row counts, flashback query window." "Flashback Query/Table, clone comparison, data merge." "Future seeded logical helper."
  register_adb_scenario "ADB04" "Incorrect UPDATE corrupts business data" "Logical recovery" "Live SQL connection, disposable lab table, before image evidence, validation query." "Flashback Versions Query, object restore, data comparison." "Future seeded logical helper."
  register_adb_scenario "ADB05" "Recover from clone" "Clone/PITR" "OCI metadata for clone permissions, source database, timestamp, compartment, and restore target." "Create clone, validate objects/application, merge recovered data." "OCI control-plane helper pending."
  register_adb_scenario "ADB06" "Point-in-time recovery drill" "Clone/PITR" "OCI PITR or clone-to-time window, backup retention, timestamp selection, and validation target." "Measure RTO/RPO, validate clone, extract/merge recovered data." "OCI control-plane helper pending."
  register_adb_scenario "ADB07" "Validate backup recoverability" "Backup readiness" "OCI backup retention, latest backup, PITR window, restore/clone capability, and evidence freshness." "Evidence-only or clone-based restore validation." "OCI control-plane helper pending."
  register_adb_scenario "ADB08" "Expired or rotated client wallet" "Connectivity" "Wallet directory, aliases, rotation owner, application distribution points, and reconnect test path." "Download new wallet, update clients, reconnect, smoke-test applications." "Plan/runbook; reconnect helper pending."
  register_adb_scenario "ADB09" "Private endpoint connectivity loss" "Network" "Private endpoint DNS/label, bastion path, routes, NSGs/security lists, and approved fault boundary." "Restore network/DNS/security-list path and validate client reconnect." "Plan/runbook; network evidence helper pending."
  register_adb_scenario "ADB10" "Connection pool saturation" "Resource limits" "Live SQL connection, approved workload limits, service-level target, and application retry/backoff boundaries." "Tune pool limits, retries, service class, and application backoff." "Plan/runbook; workload helper pending."
  register_adb_scenario "ADB11" "Resource Manager or concurrency pressure" "Resource limits" "Live SQL connection, approved workload generator, resource plan/service class, and measurable threshold." "Review service class, scaling posture, consumer limits, workload scheduling." "Plan/runbook; workload helper pending."
  register_adb_scenario "ADB12" "Cross-region DR validation" "Autonomous Data Guard" "OCI Autonomous Data Guard metadata, peer/standby region, lag, failover eligibility, and app reconnect path." "Failover validation, reconnect, RTO/RPO measurement, fallback plan." "OCI/ADG helper pending."
  register_adb_scenario "ADB13" "Autonomous Data Guard role transition" "Autonomous Data Guard" "OCI ADG role, region, lag, switchover/failover eligibility, URL/service validation." "Switchover/failover and fallback runbook." "OCI/ADG helper pending."
  register_adb_scenario "ADB14" "IAM administrator access misconfiguration" "OCI/IAM" "Read-only IAM policy/group/compartment evidence, break-glass account, and approved test boundary." "Restore IAM access and validate admin and automation access." "Plan/runbook; IAM helper pending."
  register_adb_scenario "ADB15" "Object Storage export dependency unavailable" "Object Storage" "Bucket, credential, DBMS_CLOUD object, network path, IAM policy, and export/import procedure evidence." "Restore bucket/policy/credential/network access; validate export/import." "Plan/runbook; object-storage helper pending."
  register_adb_scenario "ADB16" "Database Actions unavailable" "Application access" "Database Actions URL, SQL probe, OCI service state, wallet/connectivity, and administrator access evidence." "Restore Database Actions/ORDS access path, validate SQL/API access, and capture application smoke evidence." "Plan/runbook; URL smoke helper pending."
  register_adb_scenario "ADB17" "APEX workspace unavailable" "APEX" "APEX URL, workspace/application inventory, SQL probe, runtime users, and browser/login smoke-test path." "Restore workspace/application access, validate runtime users and application login." "Plan/runbook; browser helper pending."
  register_adb_scenario "ADB18" "Cross-region clone validation" "Clone/PITR" "OCI metadata for supported clone regions, backup retention, target compartment/region, and validation timestamp." "Create cross-region clone, validate data/application access, measure elapsed time, and clean up clone." "OCI control-plane helper pending."
  register_adb_scenario "ADB19" "Wallet distribution drift" "Connectivity" "Wallet age, local bundle path, tnsnames aliases, application distribution inventory, and reconnect smoke path." "Refresh wallet distribution, rotate credentials where required, and validate all client pools." "Plan/runbook; wallet inventory helper pending."
  register_adb_scenario "ADB20" "OCI IAM token expiration" "OCI/IAM" "OCI CLI auth mode/profile, token/session freshness, break-glass path, and automation credential ownership." "Refresh/rotate OCI auth, validate control-plane access, and update automation secrets." "Plan/runbook; OCI auth helper pending."
}

