ORACLE_SID=crashdb1
ORACLE_HOME=/u02/app/oracle/product/23.0.0.0/dbhome_1
ORACLE_BASE=/u02/app/oracle
TNS_ADMIN=/u02/app/oracle/product/23.0.0.0/dbhome_1/network/admin
CRASHSIM_GRID_HOME=/u01/app/23.0.0.0/gridhome_1
CRASHSIM_GRID_USER=grid
CRASHSIM_PDB=CRASHPDB
CRASHSIM_LOG_DIR=/tmp/crashsimulator/crashsimulator_logs
CRASHSIM_AUDIT_RETAIN=yes
CRASHSIM_AUDIT_RETENTION_DAYS=90
CRASHSIM_BASELINE_TAG_PREFIX=CSIM_BASE
